#!/bin/bash

# usage: comp {file name}
# creates an executable file and compiles it 

if [ "$2" != "" ]
then
	fileName=$2
else
	fileName=${1%.*}
fi
g++ $1 -o $fileName -static -O2 -std=c++17
./$fileName
